# Generated by Django 4.0.3 on 2022-06-22 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobilevo',
            name='import_href',
            field=models.CharField(default=None, max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='automobilevo',
            name='sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='employee_num',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='sales_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='vin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sales_record', to='sales_rest.automobilevo'),
        ),
    ]
