# Generated by Django 4.0.3 on 2022-06-23 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0005_alter_automobilevo_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrecord',
            name='vin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_record', to='sales_rest.automobilevo'),
        ),
    ]
