# Generated by Django 4.0.3 on 2022-06-18 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0003_rename_vins_appointment_vin_alter_appointment_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='vin',
            new_name='vins',
        ),
        migrations.RenameField(
            model_name='automobilevo',
            old_name='vin',
            new_name='vins',
        ),
    ]
