# Generated by Django 4.0.3 on 2022-06-20 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0008_alter_appointment_technician'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apthistory',
            old_name='vins',
            new_name='vin',
        ),
        migrations.AddField(
            model_name='appointment',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apthistory',
            name='history',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='service_rest.appointment'),
            preserve_default=False,
        ),
    ]
